### PR TITLE
Harsha

### PR DESCRIPTION
**Pull request by harshakolla18**
frontend part is done!

### CODE REVIEW

**Comment by pottelidharmateja** [comment]
Hi harsha
your code is well designed and readable but you have to update many more components like adding transaction, categories and setting or sidebars and  the css for the Login and signup should be properly Done, if you have any thing or any help ask @HajiShaik or me we will help you about this...

**Comment by harshakolla18** [comment]
i have resolved the components which is useful for the dashboard interfaces and css has been inplemented.check it out and you can suggest me on this .

**Comment by HajiShaik** [comment]
in dashboard i need to minimize the page to view the all the options in the dashboard can add the sliding bar
Screenshot (109)

**Comment by praveenchanduponguru** [comment]
I have reviewed all the frontend components and noticed an issue: after signing up, the user is redirected directly to the dashboard. Instead, the redirection should go to the homepage first, followed by the user accounts page.

**Comment by harshakolla18** [comment]
i have been working on it .i will get you back once it is resolved

**Comment by pottelidharmateja** [comment]
Yeah it should be more to change in the code but its my work as I have started backend so I have fixed all the issues and you can see in the sprint-2 needed more changes to be done I will be posting you back after the work will be resolved

**Pull request closed without merging**
