### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by pottelidharmateja**

### CODE REVIEW

**Comment by harshakolla18** [comment]
It's good that you've set a specific port (5500) in server.js, but make sure this port aligns with the environment and deployment settings.

**Comment by pottelidharmateja** [comment]
I will make sure to add it

**Comment by HajiShaik** [comment]
backend is working good Dharma. you and @praveenchanduponguru can work on testcases needed for backend.

**Comment by pottelidharmateja** [comment]
There are some issues in the Backend while connecting to the front end where the localhost issues I have resolved in sprint_2 can you check like run it and check whether it works or not.. Yeah chandhu is working on it and some of the signup issues were resolved can you check with it
Screenshot 2024-10-20 at 2 36 39 AM

**Comment by praveenchanduponguru** [comment]
I have seen that login and sign pages are working fine and I have checked that it is stored in the MongoDB database and need some more dashboard interfaces I am working on writing test cases  and I will reporting as soon as possible .

**Comment by pottelidharmateja** [comment]
I will let you know once it will be resolved and their are some dependencies issues in package.json can you guys go through it you will know and suggest what to be resolved respectively who are not getting in it..

**Pull request merged**
